grails-app/conf/Config.groovy, grails-app/conf/spring/resources.groovy, grails-app/controllers/LoginController.groovy, grails-app/services/com/recomdata/security/AuthUserDetailsService.groovy, grails-app/services/org/transmartproject/security/BruteForceLoginLockService.groovy, src/groovy/com/recomdata/security/LdapAuthUserDetailsMapper.groovy, src/groovy/org/transmartproject/security/AuthSuccessEventListener.groovy, src/groovy/org/transmartproject/security/BadCredentialsEventListener.groovy, test/unit/org/transmartproject/security/BruteForceLoginLockServiceTests.groovy
Restrict brute-force login attempts. After X failed
trials an account gets locked for Y minutes.
X - brutforce.loginAttempts.allowedNumberOfAttempts (default 3)
Y - brutforce.loginAttempts.lockTimeInMinutes (default 10)
=> Lock account temp-y after some failed login trials

web-app/js/datasetExplorer/datasetExplorer.js
The resizing of the dataAssociationPanel somehow triggers resizing of the gui in the acgh analyses. It would be ok if this was the correct size, but it is not.
=> Fix undesired resizing effects in gui for acgh analyses.

grails-app/controllers/UserGroupController.groovy
Steps to reproduce error:
- Create a new group
- Go to 'Access Control by Group'
- Search for the group in the autosuggest text field
- Add a study to it from available studies
- Go to the 'Group List'
- Select the group and delete it
Expected: Group should be deleted
Actual: Error occurs ("An error has occurred"),
though group seems to be deleted from group list,
but is still available in 'access control by group'.
=> Remove access details first before removing group

grails-app/services/I2b2HelperService.groovy
@fguitton @forus @timdo @pandis83 
This pull request concerns a Grid View visualization proposal to embed a (non-numeric) observation, in case it represents a URL, in a HTML Link format. This would allow a tranSMART user to click on those Grid View cells and follow the hyperlink (which e.g. is a reference to image data of a patient or raw molecular data from a sample of a patient).
No specific assumptions are made about the observations nor the observations' concepts. Every observation which is a well formed URL, is embedded in a HTML Link.
A use case for this feature would be: A prostate cancer study collects both clinical data of the patients as well as MR images of the patient's prostate. The MR images are stored in an image archive and read by radiologists who score the lesions …
=> Embed URL in HTML Link

web-app/js/datasetExplorer/datasetExplorer.js, web-app/js/datasetExplorer/ext-i2b2.js
Implemented in the client code because the server-side code is rather
convoluteid and this is all feel-good stuff anyway. Currently there are
no server-side enforced checks on the tree traversal, only in other
areas such as cohort building and anaylisis running.
=> Across trial nodes should never be locked

grails-app/services/com/recomdata/transmart/data/export/HighDimExportService.groovy, src/groovy/org/transmartproject/export/AcghBedExporter.groovy, src/groovy/org/transmartproject/export/TabSeparatedExporter.groovy, src/groovy/org/transmartproject/export/VCFExporter.groovy, test/integration/org/transmart/dataexport/HighDimExportServiceTests.groovy, test/unit/org/transmart/dataexport/HighDimExportServiceUnitTests.groovy, test/unit/org/transmartproject/export/AcghBedExporterTests.groovy, test/unit/org/transmartproject/export/TabSeparatedExporterTests.groovy, test/unit/org/transmartproject/export/VCFExporterTests.groovy
- Place the data file under the folder which path resemble
the path of the exported node
- Add data type to just before extension:
e.g. data_mrna.tsv
=> Improve naming/placing of the exported HD files

grails-app/conf/Config.groovy
If any error occurs while loading external configuration files is silently fails because Transmart default configuration logs only errors, but ConfigurationHelper logs errors for external configuration files at WARN level. With this minor fix its greatly simplifies error detection in external configuration files.
=> Add WARN logging for ConfigurationHelper

grails-app/services/com/recomdata/transmart/asynchronous/job/AsyncJobService.groovy
updateStatus and updateJobInputs are called from different threads at
almost the same point, updateJobInputs from the http thread and
updateStatus from the quartz thread (and later also from another http
thread as a response to checkstatus calls from the client, but this is
not relevant).
If the updateJobInputs transaction results are not visible on the
transaction on the quartz thread at the point where the quartz thread
issues the SELECT statement that precedes the UPDATE statement, then the
Hibernate session running on the quartz thread will cache stale data for
the input params column and will include this value in all the updates
thenceforth.
This fix moves the update in the http thread (done in Rmodules) and
commits the transaction before the quartz thread code is run (done in …
=> Fix race condition in jobs

src/groovy/com/recomdata/security/ActiveDirectoryLdapAuthenticationExtension.groovy
I found error in pointcut definition for ActiveDirectoryLdapAuthenticationExtension. FQ class name incorrectly contains `ad` package.
=> Fix pointcut definition for AD extension

src/groovy/com/recomdata/security/ActiveDirectoryLdapAuthenticationExtension.groovy
Sorry for spamming you with pull requests, but I find one more bug for ActiveDirectoryLdapAuthenticationExtension.
=> Fix point invocation for AD extension

grails-app/services/PlinkService.groovy, grails-app/services/com/recomdata/transmart/data/export/ExportMetadataService.groovy, grails-app/services/com/recomdata/transmart/data/export/ExportService.groovy, grails-app/services/com/recomdata/transmart/data/export/SnpDataService.groovy, web-app/js/datasetExplorer/exportData/dataTab.js
When SNP node selected then Export page fails because export metadata format was changed. Also exporters for SNP data formats doesn't work with latest database structure. This fix requires changes in transmart-core-db (https://github.com/transmart/transmart-core-db/pull/37)
=> Fix SNP export

grails-app/conf/spring/resources.groovy, grails-app/controllers/PluginDetectorController.groovy, grails-app/views/datasetExplorer/datasetExplorer.gsp, src/groovy/com/recomdata/extensions/ExtensionsRegistry.groovy, web-app/js/datasetExplorer/datasetExplorer.js
The current approach is to add new tab to analysis is to hard-code piece of code in dataExplorer.js:
```javascript
loadPlugin('dalliance-plugin', "/Dalliance/loadScripts", function () {
loadDalliance(resultsTabPanel);
}).always(function () {
// Keep loading order to prevent tabs shuffling
if (GLOBAL.metacoreAnalyticsEnabled) {
loadPlugin('transmart-metacore-plugin', "/MetacoreEnrichment/loadScripts", function () {
loadMetaCoreEnrichment(resultsTabPanel);
});
}
});
```
It is unclear and requires transmartApp codebase modification each time when we want to add new plug-in. Even more, if we need to add our custom plug-in, then we have to create fork or branch with these modifications.
I guess it is much better to add some extension points to TransmartApp and let plug-ins to register at these …
=> Support extension mechanism for plugins

grails-app/views/layouts/_commonheader.gsp, grails-app/views/layouts/_headertab.gsp, src/groovy/com/recomdata/extensions/ExtensionsRegistry.groovy
Other part of UI which is often a subject for extension is header tabs. I added to `ExtensionsRegistry` a new method for plug-ins: `registerTab`.
```groovy
void registerTab(Map<String, Object> config = [:], String id, String title, String controller)
```
It has 3 required arguments and optional config:
* id - tab identifier
* title - tab title
* controller - controller used to handle tab action
* config - now supports only one option: `insertBefore`, which can be either `String` or `Collection` with other tabs identifiers. It may be used for order resolving between tabs. 
For example, if we want to place "Dashboard" tab before first tab we can use following statement:
```groovy
transmartExtensionsRegistry.registerTab('dashboard', 'Dashboard', 'myDashboard', insertBefore: ['rwg', …
```
=> Add extension tabs support

grails-app/views/datasetExplorer/datasetExplorer.gsp, web-app/js/datasetExplorer/datasetExplorer.js
Removed hard code call transmart-metacore-plugin. Required dependency https://github.com/baroleg/transmart-metacore-plugin/tree/replaced_metacore_to_plugin
=> Replaced call metacore-plugin from transmart to the plugin

grails-app/controllers/com/recomdata/transmart/data/export/DataExportController.groovy, grails-app/services/ChartService.groovy, grails-app/views/chart/_subsetCharts.gsp, grails-app/views/chart/_valueComparison.gsp, web-app/js/datasetExplorer/datasetExplorer.js
@forus 
This pull-request addresses some robustness and consistency issues with the summary statistics in case one of the subsets is not defined.
Assumptions that if a subset is defined, it must be subset1, have been removed. These assumptions, for example, caused that the wrong color was used when drawing the histograms. Also the 'Export to Excel' button in GridView is not shown in that situation, and the Export Tab will show a message that no subsets are selected.
Also errors and/or the presence of incomplete UI elements have been addressed that are introduced if not a single observation of a concept exists for a well-defined subset. This situation will, for example, always occur for the concept that is used to exclude subjects from a subset.
In the summary statistics, the Pie-charts …
=> More robust summary statistics in case one of the subsets is not defined

src/groovy/com/recomdata/security/LdapAuthUserDetailsMapper.groovy
Introduce 2 config options for LDAP:
- `transmartproject.ldap.caseInsensitive`: enable a way to login in a case insensitive way
- `transmartproject.ldap.doNotCreateUserIfNotExist`: don’t create user if the user does not already exists in transmart DB
=> Improvments: Configurable LDAP user creation and case insensitive login

grails-app/controllers/AuthUserController.groovy
Introducing "transmartproject.authUser.create.passwordRequired" config parameter which can disable the requirement for a password (typically when transmart is used with external user management like LDAP).
=> Introducing "transmartproject.authUser.create.passwordRequired" config

web-app/js/datasetExplorer/omicsFilter.js, web-app/js/datasetExplorer/querypanels.js
Hidome Feature: when search term left empty, you get a 'no-value' typ…e filter. I.e. match all subjects who have the high dimensional concept (a.k.a. the original pre-Hidome behavior)
Fix: when entering numeric values manually in the min and max boxes, they are no longer compared as strings.
=> Hidome no-value feature + manual bounds entry fix

grails-app/controllers/ChartController.groovy, grails-app/controllers/HighDimensionFilterController.groovy, grails-app/services/ChartService.groovy, grails-app/services/HighDimensionQueryService.groovy, grails-app/services/I2b2HelperService.groovy, web-app/js/datasetExplorer/omicsFilter.js
Fix dialog behavior for VCF datatype: dragging into a panel leads to the 'No filter' behavior. Right-clicking and choosing Set filter shows the not supported yet message.
Fix concept count bar charts not showing up in summary statistics when using the 'No filter' dialog option.
Fix grid view columns for high dimensional nodes not appearing when using the 'No filter' dialog option
Fix uncaught exceptions when specifying constraints that lead to an empty patient set.
Fix bug related to using only Subset 2 with high dimensional data
=> Fixes for HiDome

grails-app/controllers/SubsetController.groovy
Fix issue: when hovering over a saved query where only subset 2 was used, the query summary tooltip window would not appear.
=> Fix an issue in Workspace (saved queries)

grails-app/domain/org/transmart/oauth2/AccessToken.groovy, grails-app/domain/org/transmart/oauth2/AuthorizationCode.groovy, grails-app/domain/org/transmart/oauth2/RefreshToken.groovy
This happens when activating both Kerberos authentication and OAuth token system.
Here is the fullstack:
```
2017-10-24 14:25:59,641 [http-apr-8080-exec-8] ERROR StackTrace  - Full Stack Trace:
grails.plugin.springsecurity.oauthprovider.exceptions.OAuth2ValidationException: Failed to save authorization code:
- Field error in object 'org.transmart.oauth2.AuthorizationCode' on field 'authentication': rejected value [[B@8558e0b]; codes [org.transmart.oauth2.AuthorizationCode.authentication.maxSize.error.org.transmart.oauth2.AuthorizationCode.authentication,org.transmart.oauth2.AuthorizationCode.authentication.maxSize.error.authentication,org.transmart.oauth2.AuthorizationCode.authentication.maxSize.error.[B,org.transmart.oauth2.AuthorizationCode.authentication.maxSize.error,authorizationCode. …
```
=> Fixing "OAuth2ValidationException: Failed to save authorization code"

grails-app/services/I2b2HelperService.groovy
16.2 seems to have lost the sorting in the legend of the pie chart on the summary tab.  This sorts the items in the table by Category.
=> Sort Pie chart legend by category

grails-app/views/layouts/_utilitiesMenu.gsp
Currently, if the user clicks off the utilities menu, it does not close.  This fix allows the user to click anywhere else on the screen and the utilities menu will close.
=> Allow user to click off the utilities menu to close it

web-app/js/datasetExplorer/i2b2common.js, web-app/panels/setValueDialog.html
We disabled gridview in our version of transmart, and were unable to clear a subset.  This is because the javascript encountered an error when trying to get the body of the gridview component (which did not exist), and could not continue.
This adds a quick check to make sure we were able to grab the body before trying to update.  
We also threw in a little code cleanup, in terms of moving the javascript out of the html.
=> Allow user to disable grid-view and still have application work 

web-app/js/datasetExplorer/datasetExplorer.js
When a user navigates to the genome browser, it changes the page title, but it does not get changed back when the user navigates away.  This will change the page title back to the default "Dataset Explorer" page title.
=> Page title reset after Genome Browser
