grails-app/controllers/UserLandingController.groovy
grails-app/views/layouts/_commonheader.gsp
test/unit/UserLandingControllerTests.groovy

Please merge https://github.com/transmart/transmart-data/pull/52 afterwards

Make hiding of tranSMART UI tabs configurable

---

grails-app/services/com/recomdata/transmart/data/export/DataExportService.groovy
grails-app/services/com/recomdata/transmart/data/export/ExportMetadataService.groovy
grails-app/services/com/recomdata/transmart/data/export/ExportService.groovy
grails-app/services/com/recomdata/transmart/data/export/HighDimExportService.groovy
test/integration/org/transmart/dataexport/DataExportControllerTests.groovy
test/integration/org/transmart/dataexport/HighDimExportServiceTests.groovy
test/unit/com/recomdata/transmart/data/export/ExportServiceXSpec.groovy
web-app/js/datasetExplorer/exportData/dataTab.js

- File per node
- Possibility to export all data for data type
- Show real patient numbers for HD instead of assays
- Frontend improvements:
- Validation of nodes data type that are dragged for exporting
- Drop box with data formats

Data Export Fixes

---

grails-app/controllers/UserGroupController.groovy
grails-app/views/userGroup/_addremove.gsp
grails-app/views/userGroup/edit.gsp
grails-app/views/userGroup/membership.gsp

Use jquery provider instead of prototype one.

Fixes for user groups modification.

---

src/groovy/org/transmartproject/export/VCFExporter.groovy
test/unit/org/transmartproject/export/VCFExporterTests.groovy

Review and merge https://github.com/transmart/transmart-core-db/pull/21 first.

Data Export: Fix VCF calculations.

---

web-app/js/datasetExplorer/exportData/dataTab.js
web-app/js/myJobs.js

Data Export - exportingdatasetexplorerfindings.htm
Analysis Jobs - viewingaloggedjob.htm

Fix help links

---

grails-app/views/datasetExplorer/datasetExplorer.gsp
web-app/js/datasetExplorer/datasetExplorer.js

Make hiding of sample details tab configurable

---

grails-app/controllers/org/transmartproject/app/user/ChangeMyPasswordController.groovy
grails-app/i18n/messages.properties
grails-app/views/changeMyPassword/show.gsp
grails-app/views/layouts/_utilitiesMenu.gsp
test/unit/org/transmartproject/app/user/ChangeMyPasswordCommandTests.groovy

The new menu item is added to "Utilities" menu: "Change My Password"
Administrator could constraint the strength of the user's passwords with
`user.password.strength.regex` variable in Config.groovy file. see https://github.com/transmart/transmart-data/pull/67

Page for changing user password by himself.

---

grails-app/services/com/recomdata/transmart/data/export/DataExportService.groovy

Remove line that make export runs twice.
Similar operation is already made here.
see https://github.com/transmart/transmartApp/blob/master/grails-app/services/com/recomdata/transmart/data/export/ExportService.groovy#L182.

Do not run HD export twice.

---

grails-app/conf/spring/resources.groovy
grails-app/services/com/recomdata/transmart/data/export/HighDimExportService.groovy
src/groovy/org/transmartproject/export/AcghBedExporter.groovy
src/groovy/org/transmartproject/export/HighDimExporter.groovy
src/groovy/org/transmartproject/export/TabSeparatedExporter.groovy
src/groovy/org/transmartproject/export/VCFExporter.groovy
test/integration/org/transmart/dataexport/HighDimExportServiceTests.groovy
test/unit/org/transmartproject/export/AcghBedExporterTests.groovy
test/unit/org/transmartproject/export/MockTabularResultHelper.groovy
test/unit/org/transmartproject/export/TabSeparatedExporterTests.groovy
test/unit/org/transmartproject/export/VCFExporterTests.groovy

Ticket: https://jira.ctmmtrait.nl/browse/FT-1165
for BED format specification see http://genome.ucsc.edu/FAQ/FAQformat.html#format1

BED Exporter for aCGH data.

---

grails-app/services/I2b2HelperService.groovy

@forus @kretep 
I've updated the isURL function and tried to follow the tranSMART coding guidelines.

update (partial) respecting tranSMART coding guideline

---

web-app/js/fixconsole.js

as described in http://stackoverflow.com/a/13817235/1097971

Fix fixconsole

---

grails-app/controllers/com/recomdata/transmart/data/export/DataExportController.groovy
grails-app/services/com/recomdata/transmart/asynchronous/job/AsyncJobService.groovy
grails-app/services/com/recomdata/transmart/data/export/DataExportService.groovy
test/integration/org/transmart/dataexport/DataExportControllerTests.groovy
web-app/js/datasetExplorer/datasetExplorer.js

For users with VIEW only permission for a study.

Hide export buttons for users wo export permis.

---

grails-app/services/I2b2HelperService.groovy

This change enables transmartApp to handle NULL values in patient_dimension columns.

Enable proper handling of NULL values in patient_dimension columns.

---

grails-app/services/com/recomdata/transmart/data/export/ClinicalExportService.groovy
grails-app/services/com/recomdata/transmart/data/export/HighDimExportService.groovy
test/integration/org/transmart/dataexport/ClinicalExportServiceTests.groovy
test/integration/org/transmart/dataexport/HighDimExportServiceTests.groovy

See also 
- https://github.com/transmart/transmart-core-api/pull/13
- https://github.com/transmart/transmart-core-db/pull/34

Export i2b2 tags

---

grails-app/controllers/OntologyController.groovy
grails-app/i18n/messages.properties
grails-app/views/ontology/_highDimSummary.gsp
grails-app/views/ontology/_showBrowseStudyInfo.gsp
grails-app/views/ontology/_showDefinition.gsp
grails-app/views/ontology/_showPlatform.gsp
grails-app/views/ontology/_showTags.gsp

Show a platform info in "Show Definition" popup.

---

grails-app/services/com/recomdata/transmart/data/export/HighDimExportService.groovy
src/groovy/org/transmartproject/export/TabSeparatedExporter.groovy
test/integration/org/transmart/dataexport/ClinicalExportServiceTests.groovy
test/integration/org/transmart/dataexport/FileContentTestUtils.groovy
test/integration/org/transmart/dataexport/HighDimExportServiceTests.groovy
test/unit/org/transmartproject/export/TabSeparatedExporterTests.groovy

Export samples and platform info with HD node.

---

src/groovy/org/transmartproject/export/TwoRegionExporter.groovy
test/unit/org/transmartproject/export/TwoRegionExporterTests.groovy

saskia wanted 2 files per sample

custom exporter for two region data

---

grails-app/controllers/com/recomdata/transmart/data/export/DataExportController.groovy
grails-app/services/com/recomdata/transmart/data/export/ExportService.groovy

Add more details to the data export log entry.

Data Export Audit Logging

---

grails-app/services/com/recomdata/transmart/data/export/ClinicalExportService.groovy
test/integration/org/transmart/dataexport/ClinicalExportServiceTests.groovy

Export tags for all subnodes of selected data set

---

grails-app/services/I2b2HelperService.groovy
src/java/com/recomdata/export/ExportColumn.java
web-app/js/datasetExplorer/gridView.js

@forus This pull request provides a solution to the JIRA issue FT-1270 (https://jira.ctmmtrait.nl/browse/FT-1270, TraIT Foundation Team).

show concept path (i.s.o. columnid) in GridView column header tool tip

---

grails-app/controllers/AuthUserController.groovy
grails-app/controllers/UserLandingController.groovy
grails-app/controllers/org/transmartproject/app/user/ChangeMyPasswordController.groovy
grails-app/i18n/messages.properties
grails-app/views/authUser/create.gsp
grails-app/views/authUser/edit.gsp
grails-app/views/authUser/show.gsp

To upgrade existing db you have to add new field to user table:
`alter table searchapp.search_auth_user add change_passwd boolean;`

Setting to force user to change his/her password.

---

grails-app/domain/FormLayout.groovy
grails-app/domain/RequiredUploadField.groovy

move tm_cz to searchapp cz_form_layout and required_upload_fields 
so biomart_user can access them without extra permissions

Form layout

---

web-app/js/datasetExplorer/datasetExplorer.js

updated to show SmartR

---

grails-app/conf/GlobalResources.groovy
grails-app/views/datasetExplorer/datasetExplorer.gsp

I did add the ressource in the folder management plugin

Fixing the folder management ressource

---

grails-app/controllers/com/recomdata/transmart/asynchronous/job/AsyncJobController.groovy

Popup show JSON when click Export button is fixed

Data Export progress display bug

---

src/groovy/org/transmart/authorization/QueriesResourceAuthorizationDecorator.groovy

Implement TRANSUI-189
Related pull requests created in:
transmart-core-db
transmartApp
transmart-core-api

Update RestAPI call for listing cohorts to not include patients

---

grails-app/views/login/auth.gsp

Use `ui.loginScreen.disclaimer` in the config file to specify the message.
Merge following PR as well: https://github.com/transmart/transmart-data/pull/149

Add customized disclaimer to the login screen.

---

grails-app/conf/BuildConfig.groovy
grails-app/controllers/ChartController.groovy

Fixed an erroneous merge that resulted in a few missing lines of code. Also merged an earlier improvement for auto-complete in hidome dialog into this branch.

Fixed an erroneous merge

---

grails-app/conf/UrlMappings.groovy

Implement TRANSUI-165
Pull request added to transmart-rest-api branch as well (already merged to gb-dev).

Add versioning of the REST API

---

web-app/js/datasetExplorer/workspace.js

Fix "Save Comparison" frontend

Access overwritten version of jquery with alias.

---

grails-app/services/I2b2HelperService.groovy

- Fixed an issue where highdimension filter dialog displayed incorrect subject count when changing the limits
- Fixed an issue where for some highdimensional data types the constraint was not displayed in Comparison and Summary Statistics tabs

Two UI fixes to high dimensional filter

---

grails-app/services/ChartService.groovy
grails-app/views/RWG/_extSearchField.gsp
grails-app/views/RWG/_extTagSearchField.gsp
grails-app/views/uploadData/_extDiseaseSearchField.gsp
grails-app/views/uploadData/_extSearchField.gsp
web-app/js/datasetExplorer/datasetExplorer.js
web-app/js/datasetExplorer/omicsFilter.js
web-app/js/rwgsearch.js

Feature/hidome tmf16.2

---

grails-app/conf/BuildConfig.groovy
grails-app/conf/Config.groovy
grails-app/conf/spring/resources.groovy
src/groovy/org/transmart/SavedRequestAwareAndResponseHeaderSettingKerberosAuthenticationSuccessHandler.groovy

Bring back Kerberos support to tranSMART

Fix kerberos

---

web-app/js/datasetExplorer/omicsFilter.js

Fixed issue where in some cases the subject with smallest or largest expression value would not be able to be included in cohort selection on high dimensional data

HiDome fix

---

grails-app/services/ChartService.groovy
grails-app/services/I2b2HelperService.groovy

Clicking the show histogram button would result in an internal server error.

Fix for histogram in select value dialog

---

web-app/js/datasetExplorer/omicsFilter.js

Fixed issue with slider in omics filter screen for negative expression values (e.g. in log expression).

Fixed issue with slider in omics filter screen

---

web-app/js/datasetExplorer/omicsFilter.js
web-app/js/datasetExplorer/querypanels.js

Fixed restoring a saved comparison from the workspace.

Fixed restore comparison from workspace

---

web-app/js/rwgsearch.js

Fixing an issue linked with SmartR importation of another version of jQuery: after a click on "Advanced Workflow", we could no more use the "Clear" button of "Active Filters", nor click on the result of an auto-completing search in the top left search text box.

Fixing an issue linked with SmartR importation of another version of jQuery

---

grails-app/conf/BuildConfig.groovy
grails-app/services/I2b2HelperService.groovy

Fix for query in getObservationCountForConceptForSubset.
Add the gwas-plink plugin to BuildConfig.groovy

Fix in getObservationCountForConceptForSubset

---

grails-app/services/I2b2HelperService.groovy

Render concept as html link it it's one when the concept folder is dragged and dropped.

Reuse making links on folde dnd as well.

---

grails-app/views/login/auth.gsp
grails-app/views/uploadData/uploadData.gsp

Reference correct variables from Config.groovy for administrator email addresses.

Reference correct variables from Config.groovy for administrator email addresses.

---

grails-app/conf/BuildConfig.groovy
grails-app/controllers/ChartController.groovy
grails-app/services/ChartService.groovy
grails-app/services/HighDimensionQueryService.groovy
grails-app/services/I2b2HelperService.groovy

If a user does not have access to a study normally, they should also not be able to see data from that study in Across Trials.  This adds that additional layer of security to completely hide studies from users who do not have permission.

Across trials security
